version: "3.5"

services:
  app:
    build: .
    image: deadlock/lock-money:latest
    restart: always
    network_mode: host
    volumes:
      - ./:/app
    environment:
      DB_URI: postgresql+psycopg://lockmoney:lockmoney-pass@localhost:5432/lockmoney
      REDIS_URI: redis://localhost:6379/0
    command: ./run-prod.sh
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    network_mode: host
    restart: always
    environment:
      POSTGRES_PASSWORD: lockmoney-pass
      POSTGRES_USER: lockmoney
      POSTGRES_DB: lockmoney
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    network_mode: host
