"""Initial revision

Revision ID: 17cd72ee5cdc
Revises: 
Create Date: 2023-04-14 23:54:08.496204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cd72ee5cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.String(length=64), nullable=False),
    sa.Column('totp_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('NATIVE', 'BANK_ACCOUNT', 'BANK_CARD'), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=128), nullable=True),
    sa.Column('bank_card_number', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_account_id', sa.BigInteger(), nullable=False),
    sa.Column('to_account_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('2fa_required', 'success', 'failed'), nullable=False),
    sa.Column('transition_token_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user_account')
    op.drop_table('user')
    # ### end Alembic commands ###
