"""Initial revision

Revision ID: 33b0e9bb24da
Revises: 
Create Date: 2023-04-15 20:12:53.419045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b0e9bb24da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_app',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=False),
    sa.Column('totp_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('initial_balance', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_account_id', sa.BigInteger(), nullable=True),
    sa.Column('to_account_id', sa.BigInteger(), nullable=True),
    sa.Column('to_bank', sa.String(), nullable=True),
    sa.Column('from_bank', sa.String(), nullable=True),
    sa.Column('to_bank_account_number', sa.String(length=128), nullable=True),
    sa.Column('from_bank_account_number', sa.String(length=128), nullable=True),
    sa.Column('from_name', sa.String(length=128), nullable=True),
    sa.Column('to_name', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'pending', name='TransactionStatus'), nullable=False),
    sa.Column('transition_token_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trusted_app_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['trusted_app_id'], ['trusted_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user_account')
    op.drop_table('user')
    op.drop_table('trusted_app')
    # ### end Alembic commands ###
