"""Add trusted app

Revision ID: d20224db86f5
Revises: 4bb45f6e0461
Create Date: 2023-04-15 11:46:29.563056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20224db86f5'
down_revision = '4bb45f6e0461'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_app',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('transaction', sa.Column('trusted_app_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'trusted_app', ['trusted_app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'trusted_app_id')
    op.drop_table('trusted_app')
    # ### end Alembic commands ###
